from __future__ import annotations

from typing import Literal

TITLE_WINDOW_LABELS = Literal["Peak Window", "Fading Window", "Outside Window"]

TITLE_WINDOW_WEIGHTS = {
    "ceiling": 0.60,
    "stability": 0.25,
    "depth": 0.15,
}

PEAK_WINDOW_THRESHOLD = 0.65
FADING_WINDOW_THRESHOLD = 0.35

TITLE_WINDOW_FRAGILITY_BOOST = 0.15

HYGIENE_MAX_SUGGESTIONS_PER_TYPE = 5

HYGIENE_ACTION_TYPES = Literal[
    "consolidate",
    "cut",
    "stash",
    "taxi",
    "hold",
    "shop",
    "package",
    "handcuff_speculative",
    "reroll_into_pick",
    "throw_in_now",
]

ELITE_INSULATION_THRESHOLD = 0.65
CONTENDER_TIER_FRACTION = 0.33
LINEUP_TARGET_POOL_FRACTION = 0.40
PLAYOFF_TARGET_PERCENTILE = 0.60
TITLE_TARGET_PERCENTILE = 0.75
ELITE_TARGET_PERCENTILE = 0.90
TE_NON_PREMIUM_URGENCY_WEIGHT = 0.6
UPGRADE_LEVERAGE_BASE_EQUITY = 0.08
AGE_CLIFF_PROXIMITY_SEASONS = 2
LINEUP_CURRENT_STRENGTH_CEILING_WEIGHT = 0.65
LINEUP_CURRENT_STRENGTH_SHORT_TERM_WEIGHT = 0.20
LINEUP_CURRENT_STRENGTH_FLOOR_WEIGHT = 0.15
LINEUP_CURRENT_STRENGTH_ADJUSTMENT_MULTIPLIER = 10.0
LINEUP_CURRENT_STRENGTH_MIN_ADJUSTMENT = -1.5
LINEUP_CURRENT_STRENGTH_MAX_ADJUSTMENT = 3.5

CUT_VALUE_FLOOR = 0.10

STASH_AGE_CEILING = 24
STASH_CEILING_FLOOR = 0.30
