/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as DraftRoomRouteImport } from './routes/draft-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'
import { Route as LeagueLeagueIdWaiversRouteImport } from './routes/league.$leagueId.waivers'
import { Route as LeagueLeagueIdTradeHistoryRouteImport } from './routes/league.$leagueId.trade-history'
import { Route as LeagueLeagueIdStartupRouteImport } from './routes/league.$leagueId.startup'
import { Route as LeagueLeagueIdRosterMovesRouteImport } from './routes/league.$leagueId.roster-moves'
import { Route as LeagueLeagueIdRookieBoardRouteImport } from './routes/league.$leagueId.rookie-board'
import { Route as LeagueLeagueIdPlayerRankingsRouteImport } from './routes/league.$leagueId.player-rankings'
import { Route as LeagueLeagueIdOrphanIntakeRouteImport } from './routes/league.$leagueId.orphan-intake'
import { Route as LeagueLeagueIdManagersRouteImport } from './routes/league.$leagueId.managers'
import { Route as LeagueLeagueIdLeagueOpsRouteImport } from './routes/league.$leagueId.league-ops'
import { Route as LeagueLeagueIdDraftGradesRouteImport } from './routes/league.$leagueId.draft-grades'
import { Route as LeagueLeagueIdComparisonRouteImport } from './routes/league.$leagueId.comparison'
import { Route as LeagueLeagueIdManagersManagerIdRouteImport } from './routes/league.$leagueId.managers.$managerId'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoomRoute = DraftRoomRouteImport.update({
  id: '/draft-room',
  path: '/draft-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdWaiversRoute = LeagueLeagueIdWaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdTradeHistoryRoute =
  LeagueLeagueIdTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdStartupRoute = LeagueLeagueIdStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdRosterMovesRoute =
  LeagueLeagueIdRosterMovesRouteImport.update({
    id: '/roster-moves',
    path: '/roster-moves',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdRookieBoardRoute =
  LeagueLeagueIdRookieBoardRouteImport.update({
    id: '/rookie-board',
    path: '/rookie-board',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdPlayerRankingsRoute =
  LeagueLeagueIdPlayerRankingsRouteImport.update({
    id: '/player-rankings',
    path: '/player-rankings',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdOrphanIntakeRoute =
  LeagueLeagueIdOrphanIntakeRouteImport.update({
    id: '/orphan-intake',
    path: '/orphan-intake',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdManagersRoute = LeagueLeagueIdManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdLeagueOpsRoute = LeagueLeagueIdLeagueOpsRouteImport.update({
  id: '/league-ops',
  path: '/league-ops',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdDraftGradesRoute =
  LeagueLeagueIdDraftGradesRouteImport.update({
    id: '/draft-grades',
    path: '/draft-grades',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdComparisonRoute =
  LeagueLeagueIdComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdManagersManagerIdRoute =
  LeagueLeagueIdManagersManagerIdRouteImport.update({
    id: '/$managerId',
    path: '/$managerId',
    getParentRoute: () => LeagueLeagueIdManagersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draft-room': typeof DraftRoomRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/$leagueId/comparison': typeof LeagueLeagueIdComparisonRoute
  '/league/$leagueId/draft-grades': typeof LeagueLeagueIdDraftGradesRoute
  '/league/$leagueId/league-ops': typeof LeagueLeagueIdLeagueOpsRoute
  '/league/$leagueId/managers': typeof LeagueLeagueIdManagersRouteWithChildren
  '/league/$leagueId/orphan-intake': typeof LeagueLeagueIdOrphanIntakeRoute
  '/league/$leagueId/player-rankings': typeof LeagueLeagueIdPlayerRankingsRoute
  '/league/$leagueId/rookie-board': typeof LeagueLeagueIdRookieBoardRoute
  '/league/$leagueId/roster-moves': typeof LeagueLeagueIdRosterMovesRoute
  '/league/$leagueId/startup': typeof LeagueLeagueIdStartupRoute
  '/league/$leagueId/trade-history': typeof LeagueLeagueIdTradeHistoryRoute
  '/league/$leagueId/waivers': typeof LeagueLeagueIdWaiversRoute
  '/league/$leagueId/managers/$managerId': typeof LeagueLeagueIdManagersManagerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draft-room': typeof DraftRoomRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/$leagueId/comparison': typeof LeagueLeagueIdComparisonRoute
  '/league/$leagueId/draft-grades': typeof LeagueLeagueIdDraftGradesRoute
  '/league/$leagueId/league-ops': typeof LeagueLeagueIdLeagueOpsRoute
  '/league/$leagueId/managers': typeof LeagueLeagueIdManagersRouteWithChildren
  '/league/$leagueId/orphan-intake': typeof LeagueLeagueIdOrphanIntakeRoute
  '/league/$leagueId/player-rankings': typeof LeagueLeagueIdPlayerRankingsRoute
  '/league/$leagueId/rookie-board': typeof LeagueLeagueIdRookieBoardRoute
  '/league/$leagueId/roster-moves': typeof LeagueLeagueIdRosterMovesRoute
  '/league/$leagueId/startup': typeof LeagueLeagueIdStartupRoute
  '/league/$leagueId/trade-history': typeof LeagueLeagueIdTradeHistoryRoute
  '/league/$leagueId/waivers': typeof LeagueLeagueIdWaiversRoute
  '/league/$leagueId/managers/$managerId': typeof LeagueLeagueIdManagersManagerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draft-room': typeof DraftRoomRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/$leagueId/comparison': typeof LeagueLeagueIdComparisonRoute
  '/league/$leagueId/draft-grades': typeof LeagueLeagueIdDraftGradesRoute
  '/league/$leagueId/league-ops': typeof LeagueLeagueIdLeagueOpsRoute
  '/league/$leagueId/managers': typeof LeagueLeagueIdManagersRouteWithChildren
  '/league/$leagueId/orphan-intake': typeof LeagueLeagueIdOrphanIntakeRoute
  '/league/$leagueId/player-rankings': typeof LeagueLeagueIdPlayerRankingsRoute
  '/league/$leagueId/rookie-board': typeof LeagueLeagueIdRookieBoardRoute
  '/league/$leagueId/roster-moves': typeof LeagueLeagueIdRosterMovesRoute
  '/league/$leagueId/startup': typeof LeagueLeagueIdStartupRoute
  '/league/$leagueId/trade-history': typeof LeagueLeagueIdTradeHistoryRoute
  '/league/$leagueId/waivers': typeof LeagueLeagueIdWaiversRoute
  '/league/$leagueId/managers/$managerId': typeof LeagueLeagueIdManagersManagerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/draft-room'
    | '/opportunities'
    | '/portfolio'
    | '/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/comparison'
    | '/league/$leagueId/draft-grades'
    | '/league/$leagueId/league-ops'
    | '/league/$leagueId/managers'
    | '/league/$leagueId/orphan-intake'
    | '/league/$leagueId/player-rankings'
    | '/league/$leagueId/rookie-board'
    | '/league/$leagueId/roster-moves'
    | '/league/$leagueId/startup'
    | '/league/$leagueId/trade-history'
    | '/league/$leagueId/waivers'
    | '/league/$leagueId/managers/$managerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/draft-room'
    | '/opportunities'
    | '/portfolio'
    | '/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/comparison'
    | '/league/$leagueId/draft-grades'
    | '/league/$leagueId/league-ops'
    | '/league/$leagueId/managers'
    | '/league/$leagueId/orphan-intake'
    | '/league/$leagueId/player-rankings'
    | '/league/$leagueId/rookie-board'
    | '/league/$leagueId/roster-moves'
    | '/league/$leagueId/startup'
    | '/league/$leagueId/trade-history'
    | '/league/$leagueId/waivers'
    | '/league/$leagueId/managers/$managerId'
  id:
    | '__root__'
    | '/'
    | '/draft-room'
    | '/opportunities'
    | '/portfolio'
    | '/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/comparison'
    | '/league/$leagueId/draft-grades'
    | '/league/$leagueId/league-ops'
    | '/league/$leagueId/managers'
    | '/league/$leagueId/orphan-intake'
    | '/league/$leagueId/player-rankings'
    | '/league/$leagueId/rookie-board'
    | '/league/$leagueId/roster-moves'
    | '/league/$leagueId/startup'
    | '/league/$leagueId/trade-history'
    | '/league/$leagueId/waivers'
    | '/league/$leagueId/managers/$managerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftRoomRoute: typeof DraftRoomRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PortfolioRoute: typeof PortfolioRoute
  TradesRoute: typeof TradesRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft-room': {
      id: '/draft-room'
      path: '/draft-room'
      fullPath: '/draft-room'
      preLoaderRoute: typeof DraftRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/waivers': {
      id: '/league/$leagueId/waivers'
      path: '/waivers'
      fullPath: '/league/$leagueId/waivers'
      preLoaderRoute: typeof LeagueLeagueIdWaiversRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/trade-history': {
      id: '/league/$leagueId/trade-history'
      path: '/trade-history'
      fullPath: '/league/$leagueId/trade-history'
      preLoaderRoute: typeof LeagueLeagueIdTradeHistoryRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/startup': {
      id: '/league/$leagueId/startup'
      path: '/startup'
      fullPath: '/league/$leagueId/startup'
      preLoaderRoute: typeof LeagueLeagueIdStartupRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/roster-moves': {
      id: '/league/$leagueId/roster-moves'
      path: '/roster-moves'
      fullPath: '/league/$leagueId/roster-moves'
      preLoaderRoute: typeof LeagueLeagueIdRosterMovesRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/rookie-board': {
      id: '/league/$leagueId/rookie-board'
      path: '/rookie-board'
      fullPath: '/league/$leagueId/rookie-board'
      preLoaderRoute: typeof LeagueLeagueIdRookieBoardRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/player-rankings': {
      id: '/league/$leagueId/player-rankings'
      path: '/player-rankings'
      fullPath: '/league/$leagueId/player-rankings'
      preLoaderRoute: typeof LeagueLeagueIdPlayerRankingsRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/orphan-intake': {
      id: '/league/$leagueId/orphan-intake'
      path: '/orphan-intake'
      fullPath: '/league/$leagueId/orphan-intake'
      preLoaderRoute: typeof LeagueLeagueIdOrphanIntakeRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/managers': {
      id: '/league/$leagueId/managers'
      path: '/managers'
      fullPath: '/league/$leagueId/managers'
      preLoaderRoute: typeof LeagueLeagueIdManagersRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/league-ops': {
      id: '/league/$leagueId/league-ops'
      path: '/league-ops'
      fullPath: '/league/$leagueId/league-ops'
      preLoaderRoute: typeof LeagueLeagueIdLeagueOpsRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/draft-grades': {
      id: '/league/$leagueId/draft-grades'
      path: '/draft-grades'
      fullPath: '/league/$leagueId/draft-grades'
      preLoaderRoute: typeof LeagueLeagueIdDraftGradesRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/comparison': {
      id: '/league/$leagueId/comparison'
      path: '/comparison'
      fullPath: '/league/$leagueId/comparison'
      preLoaderRoute: typeof LeagueLeagueIdComparisonRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/managers/$managerId': {
      id: '/league/$leagueId/managers/$managerId'
      path: '/$managerId'
      fullPath: '/league/$leagueId/managers/$managerId'
      preLoaderRoute: typeof LeagueLeagueIdManagersManagerIdRouteImport
      parentRoute: typeof LeagueLeagueIdManagersRoute
    }
  }
}

interface LeagueLeagueIdManagersRouteChildren {
  LeagueLeagueIdManagersManagerIdRoute: typeof LeagueLeagueIdManagersManagerIdRoute
}

const LeagueLeagueIdManagersRouteChildren: LeagueLeagueIdManagersRouteChildren =
  {
    LeagueLeagueIdManagersManagerIdRoute: LeagueLeagueIdManagersManagerIdRoute,
  }

const LeagueLeagueIdManagersRouteWithChildren =
  LeagueLeagueIdManagersRoute._addFileChildren(
    LeagueLeagueIdManagersRouteChildren,
  )

interface LeagueLeagueIdRouteChildren {
  LeagueLeagueIdComparisonRoute: typeof LeagueLeagueIdComparisonRoute
  LeagueLeagueIdDraftGradesRoute: typeof LeagueLeagueIdDraftGradesRoute
  LeagueLeagueIdLeagueOpsRoute: typeof LeagueLeagueIdLeagueOpsRoute
  LeagueLeagueIdManagersRoute: typeof LeagueLeagueIdManagersRouteWithChildren
  LeagueLeagueIdOrphanIntakeRoute: typeof LeagueLeagueIdOrphanIntakeRoute
  LeagueLeagueIdPlayerRankingsRoute: typeof LeagueLeagueIdPlayerRankingsRoute
  LeagueLeagueIdRookieBoardRoute: typeof LeagueLeagueIdRookieBoardRoute
  LeagueLeagueIdRosterMovesRoute: typeof LeagueLeagueIdRosterMovesRoute
  LeagueLeagueIdStartupRoute: typeof LeagueLeagueIdStartupRoute
  LeagueLeagueIdTradeHistoryRoute: typeof LeagueLeagueIdTradeHistoryRoute
  LeagueLeagueIdWaiversRoute: typeof LeagueLeagueIdWaiversRoute
}

const LeagueLeagueIdRouteChildren: LeagueLeagueIdRouteChildren = {
  LeagueLeagueIdComparisonRoute: LeagueLeagueIdComparisonRoute,
  LeagueLeagueIdDraftGradesRoute: LeagueLeagueIdDraftGradesRoute,
  LeagueLeagueIdLeagueOpsRoute: LeagueLeagueIdLeagueOpsRoute,
  LeagueLeagueIdManagersRoute: LeagueLeagueIdManagersRouteWithChildren,
  LeagueLeagueIdOrphanIntakeRoute: LeagueLeagueIdOrphanIntakeRoute,
  LeagueLeagueIdPlayerRankingsRoute: LeagueLeagueIdPlayerRankingsRoute,
  LeagueLeagueIdRookieBoardRoute: LeagueLeagueIdRookieBoardRoute,
  LeagueLeagueIdRosterMovesRoute: LeagueLeagueIdRosterMovesRoute,
  LeagueLeagueIdStartupRoute: LeagueLeagueIdStartupRoute,
  LeagueLeagueIdTradeHistoryRoute: LeagueLeagueIdTradeHistoryRoute,
  LeagueLeagueIdWaiversRoute: LeagueLeagueIdWaiversRoute,
}

const LeagueLeagueIdRouteWithChildren = LeagueLeagueIdRoute._addFileChildren(
  LeagueLeagueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftRoomRoute: DraftRoomRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PortfolioRoute: PortfolioRoute,
  TradesRoute: TradesRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
