/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DraftRoomRouteImport } from './routes/draft-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'
import { Route as LeagueLeagueIdRookieBoardRouteImport } from './routes/league.$leagueId.rookie-board'
import { Route as LeagueLeagueIdManagersRouteImport } from './routes/league.$leagueId.managers'
import { Route as LeagueLeagueIdManagersManagerIdRouteImport } from './routes/league.$leagueId.managers.$managerId'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoomRoute = DraftRoomRouteImport.update({
  id: '/draft-room',
  path: '/draft-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRookieBoardRoute =
  LeagueLeagueIdRookieBoardRouteImport.update({
    id: '/rookie-board',
    path: '/rookie-board',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdManagersRoute = LeagueLeagueIdManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdManagersManagerIdRoute =
  LeagueLeagueIdManagersManagerIdRouteImport.update({
    id: '/$managerId',
    path: '/$managerId',
    getParentRoute: () => LeagueLeagueIdManagersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draft-room': typeof DraftRoomRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/$leagueId/managers': typeof LeagueLeagueIdManagersRouteWithChildren
  '/league/$leagueId/rookie-board': typeof LeagueLeagueIdRookieBoardRoute
  '/league/$leagueId/managers/$managerId': typeof LeagueLeagueIdManagersManagerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draft-room': typeof DraftRoomRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/$leagueId/managers': typeof LeagueLeagueIdManagersRouteWithChildren
  '/league/$leagueId/rookie-board': typeof LeagueLeagueIdRookieBoardRoute
  '/league/$leagueId/managers/$managerId': typeof LeagueLeagueIdManagersManagerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draft-room': typeof DraftRoomRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/$leagueId/managers': typeof LeagueLeagueIdManagersRouteWithChildren
  '/league/$leagueId/rookie-board': typeof LeagueLeagueIdRookieBoardRoute
  '/league/$leagueId/managers/$managerId': typeof LeagueLeagueIdManagersManagerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/draft-room'
    | '/portfolio'
    | '/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/managers'
    | '/league/$leagueId/rookie-board'
    | '/league/$leagueId/managers/$managerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/draft-room'
    | '/portfolio'
    | '/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/managers'
    | '/league/$leagueId/rookie-board'
    | '/league/$leagueId/managers/$managerId'
  id:
    | '__root__'
    | '/'
    | '/draft-room'
    | '/portfolio'
    | '/trades'
    | '/league/$leagueId'
    | '/league/$leagueId/managers'
    | '/league/$leagueId/rookie-board'
    | '/league/$leagueId/managers/$managerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftRoomRoute: typeof DraftRoomRoute
  PortfolioRoute: typeof PortfolioRoute
  TradesRoute: typeof TradesRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft-room': {
      id: '/draft-room'
      path: '/draft-room'
      fullPath: '/draft-room'
      preLoaderRoute: typeof DraftRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/rookie-board': {
      id: '/league/$leagueId/rookie-board'
      path: '/rookie-board'
      fullPath: '/league/$leagueId/rookie-board'
      preLoaderRoute: typeof LeagueLeagueIdRookieBoardRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/managers': {
      id: '/league/$leagueId/managers'
      path: '/managers'
      fullPath: '/league/$leagueId/managers'
      preLoaderRoute: typeof LeagueLeagueIdManagersRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/managers/$managerId': {
      id: '/league/$leagueId/managers/$managerId'
      path: '/$managerId'
      fullPath: '/league/$leagueId/managers/$managerId'
      preLoaderRoute: typeof LeagueLeagueIdManagersManagerIdRouteImport
      parentRoute: typeof LeagueLeagueIdManagersRoute
    }
  }
}

interface LeagueLeagueIdManagersRouteChildren {
  LeagueLeagueIdManagersManagerIdRoute: typeof LeagueLeagueIdManagersManagerIdRoute
}

const LeagueLeagueIdManagersRouteChildren: LeagueLeagueIdManagersRouteChildren =
  {
    LeagueLeagueIdManagersManagerIdRoute: LeagueLeagueIdManagersManagerIdRoute,
  }

const LeagueLeagueIdManagersRouteWithChildren =
  LeagueLeagueIdManagersRoute._addFileChildren(
    LeagueLeagueIdManagersRouteChildren,
  )

interface LeagueLeagueIdRouteChildren {
  LeagueLeagueIdManagersRoute: typeof LeagueLeagueIdManagersRouteWithChildren
  LeagueLeagueIdRookieBoardRoute: typeof LeagueLeagueIdRookieBoardRoute
}

const LeagueLeagueIdRouteChildren: LeagueLeagueIdRouteChildren = {
  LeagueLeagueIdManagersRoute: LeagueLeagueIdManagersRouteWithChildren,
  LeagueLeagueIdRookieBoardRoute: LeagueLeagueIdRookieBoardRoute,
}

const LeagueLeagueIdRouteWithChildren = LeagueLeagueIdRoute._addFileChildren(
  LeagueLeagueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftRoomRoute: DraftRoomRoute,
  PortfolioRoute: PortfolioRoute,
  TradesRoute: TradesRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
